# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddToCart():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addToCart(self):
        print("Membuka: https://magento.softwaretestingboard.com/ ...")
        self.driver.get("https://magento.softwaretestingboard.com/")
        self.driver.set_window_size(654, 672)
        try:
          self.driver.find_element(
              By.CSS_SELECTOR, ".product-item:nth-child(6) .product-image-photo").click()
        except:
          print()

        try:
            self.driver.find_element(By.ID, "product-addtocart-button").click()
            print("Melakukan penambahan produk ke keranjang")
        except:
            print("Gagal menambahkan produk ke keranjang")

        self.driver.execute_script("window.scrollTo(0,552)")
        time.sleep(15)
        self.driver.find_element(
            By.XPATH, "/html/body/div[1]/main/div[1]/div[2]/div/div/div/a").click()
        print("Berhasil sampai aktivitas terakhir")
