# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddToCartWithVariant():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addToCartWithVariant(self):
        self.driver.get("https://magento.softwaretestingboard.com/")
        self.driver.set_window_size(654, 672)
        try:
            self.driver.find_element(
                By.CSS_SELECTOR, ".product-item:nth-child(1) .product-image-photo").click()
        except:
            print()
        
        time.sleep(5)

        self.driver.execute_script("window.scrollTo(0,6)")
        self.driver.find_element(
            By.XPATH, "/html/body/div[1]/main/div[2]/div/div[1]/div[4]/form/div[1]/div/div/div[1]/div/div[5]").click()
        print("Memilih ukuran")
        
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(
            By.ID, "option-label-color-93-item-57").click()
        print("Memilih warna ungu")
        self.driver.execute_script("window.scrollTo(0,0)")

        try:
            self.driver.find_element(By.ID, "product-addtocart-button").click()
            print("Melakukan penambahan produk ke keranjang")
        except:
            print("Gagal menambahkan produk ke keranjang")

        time.sleep(10)

        element = self.driver.find_element(By.ID, "product-addtocart-button")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        time.sleep(10)

        self.driver.find_element(
            By.XPATH, "/html/body/div[1]/main/div[1]/div[2]/div/div/div/a").click()

        time.sleep(5)
        getElement = self.driver.find_element(
            By.XPATH, "/html/body/div[1]/main/div[3]/div/div[2]/form/div[1]/table/tbody/tr[1]/td[1]/a/span/span/img")

        print("Penambahan produk ke keranjang berhasil")

        if "purple" in getElement.get_attribute("src"):
          print("✅ Gambar produk yang berada di keranjang sesuai")
        else:
          print("❌ Gambar produk di keranjang tidak sesuai ("+getElement.get_attribute("src")+")")